// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface AckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chain.AckResponse)
    com.google.protobuf.MessageOrBuilder {
}
