// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface AckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chain.AckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the last ack that has been seen
   * </pre>
   *
   * <code>uint32 xid = 1;</code>
   */
  int getXid();
}
