// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public final class Chain {
  private Chain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_IncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_IncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_HeadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_HeadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_StateTransferRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_StateTransferRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_StateTransferRequest_StateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_StateTransferRequest_StateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_StateTransferResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_StateTransferResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_AckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_AckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chain_AckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chain_AckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013chain.proto\022\005chain\"+\n\nIncRequest\022\013\n\003ke" +
      "y\030\001 \001(\t\022\020\n\010incValue\030\002 \001(\005\"\032\n\014HeadRespons" +
      "e\022\n\n\002rc\030\001 \001(\r\"\031\n\nGetRequest\022\013\n\003key\030\001 \001(\t" +
      "\"(\n\013GetResponse\022\n\n\002rc\030\001 \001(\r\022\r\n\005value\030\002 \001" +
      "(\005\";\n\rUpdateRequest\022\013\n\003key\030\001 \001(\t\022\020\n\010newV" +
      "alue\030\002 \001(\005\022\013\n\003xid\030\003 \001(\r\"\034\n\016UpdateRespons" +
      "e\022\n\n\002rc\030\001 \001(\r\"\254\001\n\024StateTransferRequest\0225" +
      "\n\005state\030\001 \003(\0132&.chain.StateTransferReque" +
      "st.StateEntry\022\013\n\003xid\030\002 \001(\r\022\"\n\004sent\030\003 \003(\013" +
      "2\024.chain.UpdateRequest\032,\n\nStateEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\r:\0028\001\"#\n\025StateTra" +
      "nsferResponse\022\n\n\002rc\030\001 \001(\r\"\031\n\nAckRequest\022" +
      "\013\n\003xid\030\001 \001(\r\"\r\n\013AckResponse2G\n\020HeadChain" +
      "Replica\0223\n\tincrement\022\021.chain.IncRequest\032" +
      "\023.chain.HeadResponse2@\n\020TailChainReplica" +
      "\022,\n\003get\022\021.chain.GetRequest\032\022.chain.GetRe" +
      "sponse2\272\001\n\007Replica\0225\n\006update\022\024.chain.Upd" +
      "ateRequest\032\025.chain.UpdateResponse\022J\n\rsta" +
      "teTransfer\022\033.chain.StateTransferRequest\032" +
      "\034.chain.StateTransferResponse\022,\n\003ack\022\021.c" +
      "hain.AckRequest\032\022.chain.AckResponseB\030\n\024e" +
      "du.sjsu.cs249.chainP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_chain_IncRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chain_IncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_IncRequest_descriptor,
        new java.lang.String[] { "Key", "IncValue", });
    internal_static_chain_HeadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chain_HeadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_HeadResponse_descriptor,
        new java.lang.String[] { "Rc", });
    internal_static_chain_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chain_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_chain_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chain_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_GetResponse_descriptor,
        new java.lang.String[] { "Rc", "Value", });
    internal_static_chain_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chain_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_UpdateRequest_descriptor,
        new java.lang.String[] { "Key", "NewValue", "Xid", });
    internal_static_chain_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_chain_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_UpdateResponse_descriptor,
        new java.lang.String[] { "Rc", });
    internal_static_chain_StateTransferRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_chain_StateTransferRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_StateTransferRequest_descriptor,
        new java.lang.String[] { "State", "Xid", "Sent", });
    internal_static_chain_StateTransferRequest_StateEntry_descriptor =
      internal_static_chain_StateTransferRequest_descriptor.getNestedTypes().get(0);
    internal_static_chain_StateTransferRequest_StateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_StateTransferRequest_StateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_chain_StateTransferResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_chain_StateTransferResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_StateTransferResponse_descriptor,
        new java.lang.String[] { "Rc", });
    internal_static_chain_AckRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_chain_AckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_AckRequest_descriptor,
        new java.lang.String[] { "Xid", });
    internal_static_chain_AckResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_chain_AckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chain_AckResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
