// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface StateTransferResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chain.StateTransferResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * rc = 0 means success, rc = 1 i'm not a new tail
   * </pre>
   *
   * <code>uint32 rc = 1;</code>
   */
  int getRc();
}
