// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chain.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * NOTE: this is the new calculated value. the head executes the increment
   * </pre>
   *
   * <code>int32 newValue = 2;</code>
   */
  int getNewValue();

  /**
   * <code>uint32 xid = 3;</code>
   */
  int getXid();
}
